// Arquivo gerado automaticamente por scripts/build-content.js
// Não edite manualmente. Execute `node scripts/build-content.js` para regenerar.

const MUSIC_DATA = [
  {
    "data": "1100",
    "título": "CARMINA BURANA",
    "autor": "CARL OFF",
    "musica": "O FORTUNA, IMPERATRIX MUNDI",
    "genero": "Clássica",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1700",
    "título": "BACH",
    "autor": "BACH",
    "musica": "TOCCATA & FUGUE IN DM",
    "genero": "Clássica",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1771",
    "título": "MINUETO",
    "autor": "BOCCHERINI",
    "musica": "MINUET - STRING QUINTET",
    "genero": "Clássica",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1822",
    "título": "ODE AN DIE FREUD",
    "autor": "BEETHOVEN",
    "musica": "ODE AN DIE FREUD",
    "genero": "Clássica",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1837",
    "título": "SCHERZO N2",
    "autor": "CHOPIN",
    "musica": "SCHERZO Nº 2 EM SI BEMOL MENOR",
    "genero": "Clássica",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1842",
    "título": "NABUCO",
    "autor": "GIUSEPPE VERDI",
    "musica": "VA PENSIERO ...",
    "genero": "Clássica",
    "atração musical": "1",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "1869",
    "título": "RICHARD STRAUSS",
    "autor": "RICHARD STRAUSS",
    "musica": "ALSO SPRACH ZARATHUSTRA",
    "genero": "Clássica",
    "atração musical": "1",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "1881",
    "título": "BARCAROLLE",
    "autor": "JACQUES OFFENBACH",
    "musica": "BELLE NUIT, Ô NUIT D'AMOUR",
    "genero": "Clássica",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1883",
    "título": "AS FLORES",
    "autor": "FLOWER DUET",
    "musica": "LÉO DELIBES",
    "genero": "Clássica",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1933",
    "título": "KONOMICHI",
    "autor": "H.KITAHARA",
    "musica": "KONOMKONO MICHI -THIS ROAD ICHI",
    "genero": "Étnica",
    "atração musical": "1",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1938",
    "título": "CHATEAU",
    "autor": "LUPICÍNIO RODRIUES",
    "musica": "SE ACASO VOCÊ CHEGASSE",
    "genero": "Samba",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1942",
    "título": "ESTA CHEGANDO",
    "autor": "CARMEN COSTA",
    "musica": "ESTÁ CHEGANDO A HORA",
    "genero": "Samba",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1945",
    "título": "A VIRGEM",
    "autor": "DORIS DAY",
    "musica": "SENTIMENTAL JOURNEY",
    "genero": "Jazz",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1953",
    "título": "CORDAS E HELICÓPTEROS",
    "autor": "STOCKEHAUSEN",
    "musica": "HELIKOPTER- STREICHQUARTETT",
    "genero": "Clássica",
    "atração musical": "1",
    "grau de introspecção": "1",
    "complexidade emocional": "3",
    "grau de significação": "5"
  },
  {
    "data": "1954",
    "título": "BARBERSHOP",
    "autor": "CHORDETTES",
    "musica": "MR. SANDMAN",
    "genero": "Pop Rock",
    "atração musical": "1",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "3"
  },
  {
    "data": "1956",
    "título": "CÃO DE CAÇA",
    "autor": "BIG MAMA THORNTON",
    "musica": "HOUND DOG",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1958",
    "título": "JAZZ",
    "autor": "MILES DAVIS",
    "musica": "MILESTONES",
    "genero": "Jazz",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "8"
  },
  {
    "data": "1958",
    "título": "VOLARE, NEL BLU DIPINTO DI BLU",
    "autor": "DOMENICO MODUGNO",
    "musica": "VOLARE, NEL BLU DIPINTO DI BLU",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1959",
    "título": "ARTE DE OUVIR",
    "autor": "DAVID \"DAVE\" WARREN BRUBECK",
    "musica": "TAKE FIVE",
    "genero": "Jazz",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "8"
  },
  {
    "data": "1960",
    "título": "TRINI LOPEZ",
    "autor": "TRINI LOPEZ",
    "musica": "LA BAMBA",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1961",
    "título": "BELLA CIAO",
    "autor": "RITA PAVONE",
    "musica": "BELLA CIAO",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1961",
    "título": "RITA PAVONI",
    "autor": "RITA PAVONI",
    "musica": "DATEMI UN MARTELLO",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1962",
    "título": "INSENSATEZ",
    "autor": "STAN GETZ",
    "musica": "GAROTA DE IPANEMA",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "8"
  },
  {
    "data": "1963",
    "título": "RONETTES",
    "autor": "RONETTES",
    "musica": "BE MY BABY",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1964",
    "título": "PAUL SIMON",
    "autor": "PAUL SIMON",
    "musica": "LATE IN THE EVENING",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "8"
  },
  {
    "data": "1964",
    "título": "METAFÓRICO",
    "autor": "ADORINAN BARBOSA",
    "musica": "TIRO AO ÁLVARO",
    "genero": "Samba",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1964",
    "título": "THE ANIMALS",
    "autor": "THE ANIMALS",
    "musica": "THE HOUSE OF THE RISING SUN",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1964",
    "título": "METEORO BLUE",
    "autor": "OTIS REDDING",
    "musica": "OTIS BLUE: OTIS REDDING SINGS SOUL",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1965",
    "título": "PETULA CLARK",
    "autor": "PETULA CLARK",
    "musica": "DOWNTOWN",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1966",
    "título": "THE YOUNGBLOODS",
    "autor": "THE YOUNGBLOODS",
    "musica": "GET TOGETHER",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "8"
  },
  {
    "data": "1966",
    "título": "MAMAS ANDA PAPAS",
    "autor": "MAMAS ANDA PAPAS",
    "musica": "CALIFORNIA DREAMING",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1966",
    "título": "ROLLING STONES",
    "autor": "ROLLING STONES",
    "musica": "LADY JANE",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1966",
    "título": "JOHNY RIVERS",
    "autor": "JOHNY RIVERS",
    "musica": "POOR SIDE OF TOWN",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1966",
    "título": "SERGIO MENDES",
    "autor": "SERGIO MENDES",
    "musica": "MAS QUE NADA",
    "genero": "Jazz",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1966",
    "título": "TURTLES",
    "autor": "TURTLES",
    "musica": "SURFER DAN",
    "genero": "Rock Progressivo",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1966",
    "título": "ATAQUE A CASA BRANCA",
    "autor": "GRACE SLICK",
    "musica": "WHITE RABBIT",
    "genero": "Rock Progressivo",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1966",
    "título": "TERNURINHA",
    "autor": "WANDERLEIA",
    "musica": "PARE O CASAMENTO",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1966",
    "título": "LENO E LILIAN",
    "autor": "LENO E LILIAN",
    "musica": "EU NÃO SABIA QUE VOCÊ EXISTIA",
    "genero": "MPB",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1966",
    "título": "NANCY SINATRA",
    "autor": "NANCY SINATRA",
    "musica": "THESE BOOTS ARE MADE FOR WALKIN",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1967",
    "título": "DONOVAN PHILIPS",
    "autor": "DONOVAN PHILIPS",
    "musica": "MELLOW YELLOW",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1967",
    "título": "THE SEEKERS",
    "autor": "THE SEEKERS",
    "musica": "GEORGY GIRL",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1967",
    "título": "A VOLTA DO BOÊMIO",
    "autor": "NELSON GONÇALVES",
    "musica": "A VOLTA DO BOÊMIO",
    "genero": "Samba",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1967",
    "título": "BEE GEES",
    "autor": "BEE GEES",
    "musica": "I STARTED A JOKE",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1967",
    "título": "HERMAN HERMIS",
    "autor": "HERMAN HERMIS",
    "musica": "MY SENTIMENTAL FRIEND",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1967",
    "título": "SIMONAL",
    "autor": "SIMONAL",
    "musica": "NEM VEM QUE NÃO TEM",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1967",
    "título": "THE TURTLES",
    "autor": "THE TURTLES",
    "musica": "HAPPY TOGETHER",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1967",
    "título": "TREMELOES",
    "autor": "TREMELOES",
    "musica": "SILENCE IS GOLDEN",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1967",
    "título": "LULU",
    "autor": "LULU",
    "musica": "TO SIR WITH LOVE",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1968",
    "título": "NILSSON",
    "autor": "NILSSON",
    "musica": "WITHOUT YOU",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1968",
    "título": "GERALDO VANDRE",
    "autor": "GERALDO VANDRE",
    "musica": "PARA  NÃO DIZER QUE NÃO FALEI DE FLORES",
    "genero": "MPB",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1968",
    "título": "STEVIE WONDER",
    "autor": "STEVIE WONDER",
    "musica": "SUPERSTITION",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1968",
    "título": "IAN A GADDA DA VIDA",
    "autor": "IRON BUTTERFLY",
    "musica": "IAN A GADDA DA VIDA",
    "genero": "Rock Progressivo",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1968",
    "título": "TEN YEAR AFTER",
    "autor": "TEN YEAR AFTER",
    "musica": "I'D LOVE TO CHANGE THE WORLD",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1968",
    "título": "TOMMY JAMES",
    "autor": "TOMMY JAMES",
    "musica": "CRIMSON AND CLOVER",
    "genero": "Rock Progressivo",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1969",
    "título": "ANTONIO ADOLFO E A BRAZUCA",
    "autor": "ANTONIO ADOLFO E A BRAZUCA",
    "musica": "TELETEMA",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1969",
    "título": "B. J. THOMAS",
    "autor": "B. J. THOMAS",
    "musica": "RAINDROPS KEEP FALLIN' ON MY HEAD",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1969",
    "título": "JANE BIRKIN",
    "autor": "JANE BIRKIN",
    "musica": "JE T'AIME",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1969",
    "título": "PAULO DINIZ",
    "autor": "PAULO DINIZ",
    "musica": "QUERO VOLTAR PRA BAHIA",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1969",
    "título": "SHOCKING  BLUE",
    "autor": "SHOCKING  BLUE",
    "musica": "VENUS",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1969",
    "título": "MARMALADE",
    "autor": "MARMALADE",
    "musica": "REFLECTIONS OF MY LIFE",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1969",
    "título": "THE  HOLLIES",
    "autor": "THE  HOLLIES",
    "musica": "LONG COOL WOMAN IN A BLACK DRESS",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1969",
    "título": "TOMMY ROE",
    "autor": "TOMMY ROE",
    "musica": "DIZZY",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1969",
    "título": "SANTANA",
    "autor": "SANTANA",
    "musica": "SOUL SACRIFICE",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1970",
    "título": "GAL",
    "autor": "GAL",
    "musica": "BABY",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1970",
    "título": "GRAND FUNK RAILROAD",
    "autor": "GRAND FUNK RAILROAD",
    "musica": "I'M YOUR CAPTAIN",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1970",
    "título": "BADFINGER",
    "autor": "BADFINGER",
    "musica": "NO MATTER WHAT",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1970",
    "título": "CARPENTERS",
    "autor": "CARPENTERS",
    "musica": "CLOSE TO YOU",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1970",
    "título": "PAUL MACCARTNEY",
    "autor": "PAUL MACCARTNEY",
    "musica": "ANOTHER DAY",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1970",
    "título": "PATTIE BOYD",
    "autor": "GEORGE HARRISON",
    "musica": "SOMETHING",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1970",
    "título": "ROCK PESADO",
    "autor": "MIAMI SHOWBAND",
    "musica": "CLAP YOUR HANDS",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1970",
    "título": "TERRA RARA",
    "autor": "RARE EARTH",
    "musica": "HEY BIG BROTHER",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1970",
    "título": "BOBBY BLOOM",
    "autor": "BOBBY BLOOM",
    "musica": "HEAVY MAKES YOU HAPPY",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1970",
    "título": "BREAD",
    "autor": "BREAD",
    "musica": "EVERYTHING I OWN",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1970",
    "título": "LINN ANDERSON",
    "autor": "LINN ANDERSON",
    "musica": "ROSE GARDEN",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1970",
    "título": "MUNGO JERRY",
    "autor": "MUNGO JERRY",
    "musica": "IN THE SUMMERTIME",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1970",
    "título": "SLADE",
    "autor": "SLADE",
    "musica": "GET DOWN AND GET WITH IT",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1970",
    "título": "TONY ORLANDO",
    "autor": "TONY ORLANDO",
    "musica": "CANDIDA",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1970",
    "título": "TRIO GALLETA",
    "autor": "TRIO GALLETA",
    "musica": "I'VE BEEN HURT",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1970",
    "título": "A ALMA DO RITMO",
    "autor": "THE METERS",
    "musica": "CHICKEN STRUT",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1970",
    "título": "THREE DOG NIGHT",
    "autor": "THREE DOG NIGHT",
    "musica": "MAMA TOLD ME NOT TO COME",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1971",
    "título": "LED ZEPPELIN",
    "autor": "LED ZEPPELIN",
    "musica": "OVER THE HILLS AND FAR AWAY",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1971",
    "título": "MARDI GRAS",
    "autor": "MARDI GRAS",
    "musica": "TOO BUSY THINKING ABOUT MY BABY",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1971",
    "título": "THE SWEET",
    "autor": "THE SWEET",
    "musica": "CO-CO",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "1",
    "grau de significação": "7"
  },
  {
    "data": "1971",
    "título": "THE WHO",
    "autor": "THE WHO",
    "musica": "BABA O'RILEY",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1971",
    "título": "YES",
    "autor": "YES",
    "musica": "ROUND ABOUT",
    "genero": "Rock Progressivo",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1971",
    "título": "YOU'VE GOT A FRIEND",
    "autor": "CAROLE KING",
    "musica": "YOU'VE GOT A FRIEND",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1971",
    "título": "DUBLE FANTASY",
    "autor": "JOHN LENNON",
    "musica": "DUBLE FANTASY",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1971",
    "título": "OH YOKO",
    "autor": "JOHN LENNON",
    "musica": "OH YOKO",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1971",
    "título": "ELTON JOHN",
    "autor": "ELTON JOHN",
    "musica": "CROCODILE ROCK",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1971",
    "título": "GENESIS",
    "autor": "GENESIS",
    "musica": "THE KNIFE",
    "genero": "Rock Progressivo",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1971",
    "título": "JETHRO TULL",
    "autor": "JETHRO TULL",
    "musica": "PASSION PLAY",
    "genero": "Rock Progressivo",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1971",
    "título": "TINA TURNER",
    "autor": "TINA TURNER",
    "musica": "GET BACK",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1971",
    "título": "OPS, FOI ENGANO",
    "autor": "ALICE COOPER",
    "musica": "KILLER",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1971",
    "título": "LEON RUSSEL",
    "autor": "LEON RUSSEL",
    "musica": "A SONG FOR YOU",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1971",
    "título": "LOBO",
    "autor": "LOBO",
    "musica": "ME AND YOU AND A DOG NAMED BOO",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1971",
    "título": "MIDDLE OF THE ROAD",
    "autor": "MIDDLE OF THE ROAD",
    "musica": "SACRAMENTO",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1971",
    "título": "MOUTH AND MACNEAL",
    "autor": "MOUTH AND MACNEAL",
    "musica": "HOW DO YOU DO",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1971",
    "título": "POP TOPS",
    "autor": "POP TOPS",
    "musica": "MAMY BLUE",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1971",
    "título": "PROCOL HARUM",
    "autor": "PROCOL HARUM",
    "musica": "A WHITER SHADE OF PALE",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1971",
    "título": "THE STAMPEDERS",
    "autor": "THE STAMPEDERS",
    "musica": "SWEET CITY WOMAN",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1971",
    "título": "OS IRMÃOS CANTAM",
    "autor": "CORNELIUS  BROTHERS & SISTER ROSE",
    "musica": "TREAT HER LIKE A LADY",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1972",
    "título": "DON MCLEAN",
    "autor": "DON MCLEAN",
    "musica": "AMERICAN PIE",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1972",
    "título": "DOOBIE BROTHERS",
    "autor": "DOOBIE BROTHERS",
    "musica": "LISTEN TO THE MUSIC",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1972",
    "título": "NOVOS BAIANOS",
    "autor": "NOVOS BAIANOS",
    "musica": "BRASIL PANDEIRO",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1972",
    "título": "YELLOWSTONE AND VOICE",
    "autor": "YELLOWSTONE AND VOICE",
    "musica": "PHILOSOPHER",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "1",
    "grau de significação": "7"
  },
  {
    "data": "1972",
    "título": "5TH DIMENSION",
    "autor": "5TH DIMENSION",
    "musica": "AQUARIUS / LET THE SUNSHINE IN",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1972",
    "título": "AL GREEN",
    "autor": "AL GREEN",
    "musica": "LET'S STAY TOGETHER",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1972",
    "título": "CREEDENCE",
    "autor": "CREEDENCE",
    "musica": "SAIL AWAY",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1972",
    "título": "DEEP PURBLE",
    "autor": "DEEP PURBLE",
    "musica": "SMOKE ON THE WATER",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1972",
    "título": "ROBERTA FLACK",
    "autor": "ROBERTA FLACK",
    "musica": "KILLING ME SOFTLY",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1972",
    "título": "CARLY SIMON",
    "autor": "CARLY SIMON",
    "musica": "YOU'RE SO VAIN",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1972",
    "título": "DANIEL BOONE",
    "autor": "DANIEL BOONE",
    "musica": "BEAUTIFUL SUNDAY",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1972",
    "título": "FORTUNES",
    "autor": "FORTUNES",
    "musica": "YOU GOT YOUR TROUBLES",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1972",
    "título": "GARY GLITTER",
    "autor": "GARY GLITTER",
    "musica": "SCHOOL DAY",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1972",
    "título": "THE TEMPTATIONS",
    "autor": "THE TEMPTATIONS",
    "musica": "PAPA WAS A ROLLING STONE",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1972",
    "título": "TIMMY  THOMAS",
    "autor": "TIMMY  THOMAS",
    "musica": "WHY CAN'T WE LIVE TOGETHER",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1972",
    "título": "DAVE EDMUNDS",
    "autor": "DAVE EDMUNDS",
    "musica": "I HEAR YOU KNOCKING",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1972",
    "título": "TODD RUNDGREN",
    "autor": "TODD RUNDGREN",
    "musica": "I SAW THE LIGHT",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1973",
    "título": "DISCOS MARCOS PEREIRA",
    "autor": "NARA LEÃO",
    "musica": "CALIX BENTO",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "8"
  },
  {
    "data": "1973",
    "título": "GLADYS KNIGHT & THE PIPS",
    "autor": "GLADYS KNIGHT & THE PIPS",
    "musica": "MIDNIGHT PLANE TO HOUSTON",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1973",
    "título": "OSIBISA",
    "autor": "OSIBISA",
    "musica": "ADWOA",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1973",
    "título": "SUZI QUATRO",
    "autor": "SUZI QUATRO",
    "musica": "STUMBIN ‘IN",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1973",
    "título": "TAMBORES",
    "autor": "INCREDIBLE BONGO BAND",
    "musica": "BONGO ROCK",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1973",
    "título": "ELVIS PRESLEY",
    "autor": "ELVIS PRESLEY",
    "musica": "BURNING LOVE",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1973",
    "título": "ALBERT HAMMOND",
    "autor": "ALBERT HAMMOND",
    "musica": "IF YOU GOTTA BREAK ANOTHER HEART",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1973",
    "título": "CHARLIE RICH",
    "autor": "CHARLIE RICH",
    "musica": "THE MOST BEAUTIFUL GIRL",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1973",
    "título": "PAUL BRYAN",
    "autor": "PAUL BRYAN",
    "musica": "LISTEN",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1973",
    "título": "STORIES",
    "autor": "STORIES",
    "musica": "BROTHER LOUIE",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1974",
    "título": "SUPERTRAMP",
    "autor": "SUPERTRAMP",
    "musica": "SCHOOL",
    "genero": "Rock Progressivo",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1974",
    "título": "BACHAMAN TURNER ORVERDRIVE",
    "autor": "BACHAMAN TURNER ORVERDRIVE",
    "musica": "YOU AIN'T SEEN NOTHIN YET",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1974",
    "título": "BARRY MANILOW",
    "autor": "BARRY MANILOW",
    "musica": "MANDY",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1974",
    "título": "MINNIE  RIPERTON",
    "autor": "MINNIE  RIPERTON",
    "musica": "LOVING YOU",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1974",
    "título": "PAPER LACE",
    "autor": "PAPER LACE",
    "musica": "THE NIGHT CHICAGO DIED",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1974",
    "título": "REDBONE",
    "autor": "REDBONE",
    "musica": "COME AND GET YOUR LOVE",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1974",
    "título": "THE RUBENTES",
    "autor": "THE RUBENTES",
    "musica": "SUGAR BABY LOVE",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1974",
    "título": "A LOURA",
    "autor": "BLONDIE",
    "musica": "HEART OF GLASS",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1975",
    "título": "IMPROVISADOR",
    "autor": "KEITH JARRETT",
    "musica": "THE KÖLN CONCERT",
    "genero": "Jazz",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1975",
    "título": "ARTHUR MOREIRA",
    "autor": "ARTHUR MOREIRA",
    "musica": "APANHEI-TE, CAVAQUINHO",
    "genero": "MPB",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "8"
  },
  {
    "data": "1975",
    "título": "MALDITO",
    "autor": "WALTER FRANCO",
    "musica": "SERRA DO LUAR",
    "genero": "MPB",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1975",
    "título": "CLAUDE BOLLING",
    "autor": "CLAUDE BOLLING",
    "musica": "BAROQUE AND BLUE",
    "genero": "Jazz",
    "atração musical": "1",
    "grau de introspecção": "2",
    "complexidade emocional": "3",
    "grau de significação": "6"
  },
  {
    "data": "1975",
    "título": "ABBA",
    "autor": "ABBA",
    "musica": "FERNANDO",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1975",
    "título": "10CC",
    "autor": "10CC",
    "musica": "I'M NOT IN LOVE",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1976",
    "título": "BELLAMY BROTHERS",
    "autor": "BELLAMY BROTHERS",
    "musica": "LET YOUR LOVE FLOW",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1976",
    "título": "BELLE E SABASTIAN",
    "autor": "BELLE E SABASTIAN",
    "musica": "ANOTHER SUNNY DAY",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "4"
  },
  {
    "data": "1977",
    "título": "RAUL SEIXAS",
    "autor": "RAUL SEIXAS",
    "musica": "MEDO DA CHUVA",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1978",
    "título": "KATE BUSCH",
    "autor": "KATE BUSCH",
    "musica": "WUTHERING HEIGHTS",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1978",
    "título": "BANDEIRA DE AÇO",
    "autor": "BANDEIRA DE AÇO",
    "musica": "BANDEIRA DE AÇO",
    "genero": "MPB",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1979",
    "título": "ZIGGY STARDUST",
    "autor": "DAVID BOWIE",
    "musica": "STARMAN",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "1979",
    "título": "BONEY M",
    "autor": "BONEY M",
    "musica": "RIVERS OF BABYLON",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1979",
    "título": "POLONAISE",
    "autor": "MAZOWSZE",
    "musica": "LAURA I FILON",
    "genero": "Étnica",
    "atração musical": "1",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "5"
  },
  {
    "data": "1980",
    "título": "LEGIÃO URBANA",
    "autor": "LEGIÃO URBANA",
    "musica": "PAIS E FILHOS",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1980",
    "título": "TOWSHEND",
    "autor": "THE WHO",
    "musica": "BEHIND BLUE EYES",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1981",
    "título": "UNDER PRESSURE",
    "autor": "DAVID BOWIE",
    "musica": "UNDER PRESSURE",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "8"
  },
  {
    "data": "1982",
    "título": "TOTO",
    "autor": "TOTO",
    "musica": "AFRICA",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1983",
    "título": "VIOLENTE FEMMES",
    "autor": "VIOLENTE FEMMES",
    "musica": "BLISTER IN THE SUN",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1984",
    "título": "FELIZ NATAL",
    "autor": "JOHN LENNON",
    "musica": "HAPPY XMAS",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "8"
  },
  {
    "data": "1986",
    "título": "LA GUITARRA",
    "autor": "STANLEY JORDAN",
    "musica": "ELEANOR RIGBY",
    "genero": "Jazz",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "1988",
    "título": "WILBURYS",
    "autor": "WILBURYS",
    "musica": "HANDLE WITH CARE",
    "genero": "Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "1988",
    "título": "SATIE",
    "autor": "ERIK SATIE",
    "musica": "LE TANGO PREPÉTUAL",
    "genero": "Tango",
    "atração musical": "1",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "5"
  },
  {
    "data": "1990",
    "título": "ENIGMA",
    "autor": "ENIGMA",
    "musica": "RETURN TO INNOCENCE",
    "genero": "Rock Progressivo",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "8"
  },
  {
    "data": "1991",
    "título": "TEREZA SALGUEIRO",
    "autor": "TEREZA SALGUEIRO",
    "musica": "ESTRADA DO MONTE",
    "genero": "Étnica",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "1991",
    "título": "O CEARENCE DO ESCRACHO",
    "autor": "FALCÃO",
    "musica": "BONITO, LINDO E JOIADO",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "1992",
    "título": "BOBBY MACFERIN",
    "autor": "BOBBY MACFERIN",
    "musica": "HUSH LITTLE BABY",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1993",
    "título": "ISRAEL KAMAKAWIWO'OLE",
    "autor": "ISRAEL KAMAKAWIWO'OLE",
    "musica": "OVER THE RAINBOW",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "1",
    "grau de significação": "7"
  },
  {
    "data": "1997",
    "título": "DEEP FOREST",
    "autor": "DEEP FOREST",
    "musica": "GREEN & BLUE",
    "genero": "Folk Rock",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "8"
  },
  {
    "data": "1997",
    "título": "ZE COCO DO RIACHAO",
    "autor": "ZE COCO DO RIACHAO",
    "musica": "VÔO DAS GARÇAS",
    "genero": "MPB",
    "atração musical": "1",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "1997",
    "título": "CANTORA DE RUA",
    "autor": "RACHELLE GARNIEZ",
    "musica": "SERENADE",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "1998",
    "título": "NINHO DA MÚSICA",
    "autor": "NAÏKA",
    "musica": "BEFORE HE FALLS",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "2001",
    "título": "PEAKY BLINDERS",
    "autor": "NICK CAVE AND THE BAD SEEDS",
    "musica": "RED RIGHT HAND",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "2001",
    "título": "GOTAN PROJET",
    "autor": "GOTAN PROJET",
    "musica": "SANTA MARÍA",
    "genero": "Tango",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "2002",
    "título": "EPITÁFIO",
    "autor": "TITÃS",
    "musica": "EPITÁFIO",
    "genero": "MPB",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "2002",
    "título": "BAJOFONDO",
    "autor": "BAJOFONDO",
    "musica": "A FAVORITA",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "2002",
    "título": "SALIR CORRIENDO",
    "autor": "EVA AMARAL",
    "musica": "SALIR CORRIENDO",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "2003",
    "título": "CARINHOSO",
    "autor": "MARISA MONTE",
    "musica": "CARINHOSO",
    "genero": "MPB",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "2007",
    "título": "MOINHO",
    "autor": "CARTOLA",
    "musica": "O MUNDO É UM MOINHO",
    "genero": "Samba",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "2007",
    "título": "O REI DA NOITE",
    "autor": "HAMIN DJAWADI",
    "musica": "GAME OF THRONES MAIN TITLE",
    "genero": "Clássica",
    "atração musical": "1",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "2007",
    "título": "SER DIFERENTE",
    "autor": "ARCHITECTURE IN HELSINKI",
    "musica": "ESCAPEE",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "2007",
    "título": "MIRANDA!",
    "autor": "MIRANDA!",
    "musica": "PERFECTA",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "2008",
    "título": "ANDREAS SCHOLL",
    "autor": "ANDREAS SCHOLL",
    "musica": "VENUS' BIRDS",
    "genero": "Clássica",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "2008",
    "título": "JULIETA VENEGAS",
    "autor": "JULIETA VENEGAS",
    "musica": "ME VOY",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "2008",
    "título": "CARL DOUGLAS",
    "autor": "CARL DOUGLAS",
    "musica": "KUNG FU FIGHTING",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "2009",
    "título": "NÃO DESONRE O MEU NOME",
    "autor": "PITTY",
    "musica": "ME ADORA",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "9"
  },
  {
    "data": "2009",
    "título": "ARNALDO ANTUNES",
    "autor": "ARNALDO ANTUNES",
    "musica": "A CASA É SUA",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "2011",
    "título": "A DURGA DA MARIMBA",
    "autor": "KUNIKO KATO",
    "musica": "STEVE REICH SIX MARIMBAS COUNTERPOINT",
    "genero": "Jazz",
    "atração musical": "1",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "2012",
    "título": "NOVO SOM EM MINAS",
    "autor": "ETCOETERA",
    "musica": "ALMA",
    "genero": "MPB",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "2012",
    "título": "O SOM DO MERCADO",
    "autor": "VARIOUS CRUELTIES",
    "musica": "GREAT UNKNOWN",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "2013",
    "título": "VOZES DAFRICA",
    "autor": "ROKIA TRAORÉ",
    "musica": "TU VOLES",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "7"
  },
  {
    "data": "2013",
    "título": "BARBARA",
    "autor": "BÁRBARA EUGÊNIA",
    "musica": "YOU WISH, YOU GET IT",
    "genero": "MPB",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "2013",
    "título": "MÚSICA LAGOM",
    "autor": "NONONO",
    "musica": "MASTERPIECE",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "2014",
    "título": "TENGO MIEDO",
    "autor": "MARIA RODES",
    "musica": "TENGO MIEDO",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "2014",
    "título": "ANDRES CALAMARO",
    "autor": "ANDRES CALAMARO",
    "musica": "LA PARTE DE ADELANTE",
    "genero": "Pop Rock",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "2014",
    "título": "MUSICA DO NORTE",
    "autor": "THE GARDENER & THE TREE",
    "musica": "POSTCARDS",
    "genero": "Pop Rock",
    "atração musical": "3",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "6"
  },
  {
    "data": "2014",
    "título": "YIRA, YIRA",
    "autor": "MONO MORELLO",
    "musica": "YIRA, YIRA",
    "genero": "Tango",
    "atração musical": "1",
    "grau de introspecção": "2",
    "complexidade emocional": "2",
    "grau de significação": "5"
  },
  {
    "data": "2015",
    "título": "ARQUITETO DO SOM",
    "autor": "VOLKER PANNES",
    "musica": "OPERA BIRD SONG",
    "genero": "Jazz",
    "atração musical": "1",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "6"
  },
  {
    "data": "2015",
    "título": "PAMPLAMOOSE",
    "autor": "PAMPLAMOOSE",
    "musica": "OH, PRETTY WOMAN",
    "genero": "Rock/Pop",
    "atração musical": "3",
    "grau de introspecção": "1",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "2016",
    "título": "JAZZ VINTAGE",
    "autor": "AVALON JAZZ BAND",
    "musica": "MÉNILMONTANT",
    "genero": "Jazz",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "2016",
    "título": "LA LA LAND",
    "autor": "RYAN GOSLING",
    "musica": "CITY OF STARS",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "2",
    "complexidade emocional": "1",
    "grau de significação": "5"
  },
  {
    "data": "2019",
    "título": "M A N T R A",
    "autor": "GAIEA SANSKRI",
    "musica": "BHOJANAM MANTRA",
    "genero": "Étnica",
    "atração musical": "1",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "2019",
    "título": "A MUSA",
    "autor": "LOLA ASTANOVA",
    "musica": "LA CAMPANELLA",
    "genero": "Clássica",
    "atração musical": "1",
    "grau de introspecção": "3",
    "complexidade emocional": "3",
    "grau de significação": "7"
  },
  {
    "data": "2020",
    "título": "DYLAN  - AS MÚSICAS DA MÚSICA",
    "autor": "NAT KING COLE",
    "musica": "NATURE BOY",
    "genero": "Rock/Pop",
    "atração musical": "2",
    "grau de introspecção": "3",
    "complexidade emocional": "2",
    "grau de significação": "7"
  }
];

if (typeof window !== 'undefined') {
  window.musicData = MUSIC_DATA;
}

// Nota: export removido porque o arquivo é carregado como script regular, não como módulo ES6
